### ISSUE TITLE
Different approaches to Backbone/Require startup

### ISSUE THREAD

**Issue by micros123** [jcreamer898/RequireJS-Backbone-Starter#1]
Hi, not really an issue, but an interesting point of discussion in my opinion.
I was looking at various approaches to Backbone startup with RequireJS, and had used the one by Thomas Davis, since it was relatively popular. However, I found his approach a bit confusing, especially in his router.js class, with the initialize variable in the return object. I changed it around to look more like your solution and it works fine.
So I'm mainly wondering what you think of this (popular but slightly odd) approach: https://github.com/thomasdavis/backbonetutorials/blob/gh-pages/examples/modular-backbone/js/router.js

**Comment by jcreamer898** [comment]
That is an interesting approach, my only issue is that if you need to store a reference to that router somewhere, you won't be able to because it's just.  

```
var initialize = function(){
    var app_router = new AppRouter;
    Backbone.history.start();
};
```

The `app_router` is encapsulated in the initialize function.  

So you can't do things like `router.navigate('/url')`...

**Comment by micros123** [comment]
Yeah, that variable kind of gets lost in there.
And to me, the explicit calls/returns to .initialize (which sometimes is a var outside backbone) seem a bit unnecessary, since Backbone will call the initialize function like a constructor when you instantiate a class.
After seeing your solution I was mainly wondering if you see any advantage in Thomas' that I'm missing?
