### ISSUE TITLE
Cannot call method 'template' of undefined 

### ISSUE THREAD

**Issue by eddiemoore** [jcreamer898/RequireJS-Backbone-Starter#3]
Hi I was just running the base files of your app and I am getting :
**Uncaught TypeError: Cannot call method 'template' of undefined   --   view.js:14**

It seems that underscore is undefined.

Any ideas on how to fix it?

**Comment by jcreamer898** [comment]
I left out underscore from the shim, let me know if that helps!

**Comment by eddiemoore** [comment]
Yep everything is ok now.
